name: Feature Request
description: Request a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you're requesting
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide to users or the project?
      placeholder: This would improve...
    validations:
      required: true
  - type: textarea
    id: implementation_ideas
    attributes:
      label: Implementation Ideas
      description: Any ideas for how this could be implemented?
      placeholder: Maybe by...
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority level would you assign to this feature?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of the application does this feature relate to?
      options:
        - Performance
        - User Experience
        - Architecture
        - Frontend
        - Backend
        - AI/ML
        - Security
        - Documentation
        - Other
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort do you estimate this would take?
      options:
        - Small (1-3 days)
        - Medium (1-2 weeks)
        - Large (2+ weeks)
        - Unknown
    validations:
      required: false